controllers:
<<<<<<< HEAD
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
=======
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
>>>>>>> gestion-activites
