controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
offer_create_ajax:
    path: /offre/create/ajax
    controller: App\Controller\OffreController::create
    methods: [POST]
